Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/lae-form.scss
app/controllers/catalog_controller.rb
app/views/_user_util_links.html.erb
app/views/catalog/_show_sidebar.html.erb
app/views/contacts/create.html.erb
app/views/contacts/new.html.erb
config/environments/production.rb
config/pulstore.yml
solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml

This will require a full re-index as the solr schema has changed.

Various Ui cleanup Issues / Add Date Range Slider and Sort

---

app/assets/stylesheets/lae--header.scss
app/assets/stylesheets/lae--hero-unit.scss
app/helpers/application_helper.rb
app/views/catalog/show.html.erb
app/views/pages/_featured_document.html.erb
app/views/pages/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_header_navbar.html.erb
db/schema.rb
solr_conf/conf/solrconfig.xml

Also new approach to homepage sample images.

Fluid space cleanup

---

Gemfile
Gemfile.lock
app/assets/stylesheets/facet--pivot.scss
app/helpers/blacklight_url_helper.rb
app/helpers/facets_helper.rb
app/views/catalog/_facet_pivot.html.erb
solr_conf/conf/solrconfig.xml

Some problems with this. Facets aren't a hierarchy.

Facet cleanup

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/google_analytics.js
app/models/record_mailer.rb
app/views/catalog/_document.html.erb
config/environments/production.rb

Also add google analytics #92.

Fix deprecation warnings, asset loading cleanup for openseadragon

---

Gemfile
Gemfile.lock

Try again with the right gem version.

Uglifier 2.7.2

---

README.md

Add setup and configuration instructions to README

---

README.md

Corrects small error in README.

Fix database configuration example in README

---

config/application.rb
config/deploy.rb
config/deploy/staging.rb

This allows Breakpoint to be registered as Compass::Framework so it doesn't break.

Load compass earlier.

---

.rubocop.yml
app/indexers/plum_jsonld_converter.rb
app/services/solr_document_metadata.rb
app/views/catalog/_show_default.html.erb
config/locales/en.yml
solr/conf/schema.xml
spec/fixtures/files/208_solr_docs.xml
spec/indexers/plum_jsonld_converter_spec.rb
spec/services/solr_document_metadata_spec.rb

fixes #165 and fixes #157 
NOTE: This will require a new schema to be pushed to the server. Not sure what the process for / implications of that are.

Index subj tuples

---

app/helpers/application_helper.rb
solr/conf/schema.xml

Only feature items with thumbnails.

---

app/helpers/application_helper.rb
app/indexers/plum_jsonld_converter.rb
solr/conf/schema.xml
spec/indexers/plum_jsonld_converter_spec.rb

Fix subject category index

---

app/indexers/plum_jsonld_converter.rb
solr/conf/schema.xml
spec/fixtures/files/plum_records/b9e8325e-baf2-45e4-b32c-5e5b3755c8ef.jsonld
spec/indexers/plum_jsonld_converter_spec.rb

Index more fields

---

.rubocop.yml
app/services/solr_document_metadata.rb
config/locales/en.yml

Fix order of metadata.

---

app/assets/stylesheets/facet--pivot.scss

Restores fonts of old site (sans-serif facet headings, title-case facet heading instead of uppercase)
Fixes #195

Fixing facet fonts

---

app/views/bookmarks/_tools.html.erb
app/views/search_history/index.html.erb
spec/features/search_history_spec.rb
spec/request/bookmarks_controller_spec.rb

Fixes #207 
Thanks for reporting this problem @cjcolvar !

Fix search history and bookmarks

---

app/assets/stylesheets/print.scss

Clean up print view of search results while I'm in here

Add print stylesheet; printable record view, fixes #138

---

app/indexers/plum_jsonld_converter.rb
app/services/plum_event_processor/create_processor.rb
spec/services/plum_event_processor_spec.rb

Handle Manifests returning 404s.

---

app/controllers/catalog_controller.rb

Separate multiple publishers with linebreaks instead of to_sentence defaults

---

config/locales/en.yml
spec/features/catalog_controller_spec.rb
spec/fixtures/files/solr.xml

Adding creator label

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/models/lae_export_extension.rb

Fully resolves #224 and https://github.com/pulibrary/figgy/issues/756 and adds some method documentation

Updates pul_uv_rails to clone from the "master" branch (bringing it into parity with figgy)

---

Gemfile
Gemfile.lock

- Updates ffi to 1.9.25
- Updates rubyzip to 1.2.2

Updates ffi and rubyzip

---

config/locales/en.yml
config/locales/es.yml
config/locales/pt-BR.yml

Add missing description translations

---

config/initializers/i18n.rb
spec/i18n_spec.rb

Add custom i18n exception handler to handle missing translations

---

app/assets/stylesheets/blacklight.scss
app/assets/stylesheets/lae.scss

- Increases width of labels so they aren't truncated.
- Adds formatting of description text with line breaks when viewing in Spanish and Portuguese.
Closes #253

Update metadata styling

---

app/controllers/catalog_controller.rb

Advances https://github.com/pulibrary/princeton_ansible/issues/600

update catalog controller solr params to be compatible with 7.7

---

app/indexers/reindexer.rb
spec/indexers/reindexer_spec.rb

I'm testing this in Staging right now.

Make the reindexer resilient to individual errors.

---

.circleci/config.yml

Updating the Node.js configuration to support 12.x releases

---

Gemfile
Gemfile.lock
README.md

This is necessary in order to advance #293

Updating the mimemagic Gem dependency (along with removing the `therubyracer` and `libv8` Gems)

---

.gitignore
Gemfile
Gemfile.lock
README.md

* Remove sdoc
* Add YARD
* Remove defunct banner from README

Upgrade JSON

---

.circleci/config.yml
.lando.yml
Gemfile
Gemfile.lock

Use postgres 13

---

app/indexers/reindexer.rb
lib/tasks/lae.rake
spec/indexers/reindexer_spec.rb

Allow index to some other solr url

---

README.md
app/indexers/plum_jsonld_converter.rb
app/indexers/reindexer.rb

Document production reindex

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
spec/rails_helper.rb
spec/spec_helper.rb

Coveralls wasn't running, with an ssh error. Fixing it would be another
option.
closes #347

Replace coveralls with simplecov, minimum 80%.

---

.circleci/config.yml
.lando.yml

Update postgres version in CI and lando

---

.circleci/config.yml
.tool-versions

Closes #357 
See also: https://github.com/pulibrary/princeton_ansible/pull/4452

Upgrade to node 18.18.0

---

Gemfile
Gemfile.lock
config/initializers/datadog.rb

Add Datadog APM

---

Gemfile
Gemfile.lock

Add Honeybadger.

---

config/deploy/production.rb
config/deploy/staging.rb

Migrate to Jammy

---

Gemfile
Gemfile.lock
app/checks/solr_status.rb
config/initializers/health_monitor.rb
config/routes.rb
spec/request/health_check_spec.rb

Add health checks

---

README.md

This would have made #374 easier for someone who isn't familiar with
this application

Add lae:reindex to readme

---

app/checks/smtp_status.rb
config/initializers/health_monitor.rb
spec/request/health_check_spec.rb

Add SMTP Status

---

config/initializers/health_monitor.rb

remove honeybadger notification health status

---

app/models/contact.rb

remove gmail account as contact

---

Gemfile
Gemfile.lock
config/initializers/honeybadger_downtime_hook.rb
spec/honeybadger_check_spec.rb

Add Honeybadger downtime hook

---

app/views/shared/_footer.html.erb

Adds max-width to footer

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/deploy.rb
config/initializers/health_monitor.rb
db/schema.rb
spec/features/range_limit_spec.rb

Add capistrano task to remove app from load balancer.

---

app/checks/smtp_status.rb
spec/request/health_check_spec.rb

SMTP check should happen every 5 minutes.

---

public/robots.txt

I just copied the one from the catalog. Bots are requesting it, might as well give 'em tips.

Add a basic robots.txt
